apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-097411a8fb1089384 #Replace with new volume ID, whcih is created from snapshot
    fsType: ext4
