apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      initContainers:
      - name: init-apache
        image: httpd
        command: ["/bin/sh", "-c"]
        args: ["cp -r /usr/local/apache2/* /mnt/apache2/"]
        volumeMounts:
        - name: apache-pvc
          mountPath: /mnt/apache2
      containers:
      - name: apache
        image: httpd
        ports:
        - containerPort: 80
        volumeMounts:
        - name: apache-pvc
          mountPath: /usr/local/apache2
      volumes:
      - name: apache-pvc
        persistentVolumeClaim:
          claimName: apache-pvc
