apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-071affc491c34ddcc # Replace with new volume ID, whcih is created from snapshot
    fsType: ext4
